### ISSUE TITLE
Windows10的SUI环境配置时网络不通畅的问题

### ISSUE THREAD

**Issue by 0xhutou** [movefuns/SuiStartrek#18]
挂了全局梯子，安装完rust之后在命令行运行
`cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui`
一开始挂的香港的节点，下载过程一直卡住，后来换了台湾的节点，能运行一部分，然后出现图里的问题：
![4d7b1f7bbadfbbd0543ed5761681dfc](https://github.com/movefuns/SuiStartrek/assets/106515068/ca95fe65-abf0-4dfe-a1cf-835e01ea080f)
请问怎么解决？

**Comment by d-ethan3** [comment]
1. 保证终端走了代理
2. 多换节点试试

**Comment by jeffierw** [comment]
可以看下我的[解决办法](https://www.notion.so/jeffierw/SuiStartrek-Problems-b0a25bbaefe14b679f71d0bf17e27e5a)

**Comment by upupnoah** [comment]
命令行需要执行一下命令才能走代理：
```
set http_proxy=http://your-proxy-address:port
set https_proxy=https://your-proxy-address:port
```

**Comment by summertoo** [comment]
走代理试试看,windows10的确需要走一下代理
