### ISSUE TITLE
星航计划加入申请

### ISSUE THREAD

**Issue by crazythree20** [movefuns/SuiStartrek#55]
### 个人介绍
工作是运维，用python比较多，想学习movesui，对web3感兴趣，但是没有入门点
* Github ID: [github](https://github.com/crazythree20)

* Telegram ID: @c_razyt

* Discord ID: crazythree21

(首次如果没有，学习完毕钱包在填写)
* Sui 账号地址: 0x571b0277621ad4d4c991321b265c69fa5930039ef3b4b042339d5a861db9a44f

**Comment by taramakage** [comment]
请Fork仓库，以PR方式提交申请。
